import Voter
#print axioms Voter.transition_product
#print axioms Voter.transition_product_bool
#print axioms Voter.iterate_mass
#print axioms Voter.possible_consensus
#print axioms Voter.consensus_tendsto
#print axioms Voter.consensus_probability
#print axioms Voter.uniform_consensus_probability
#print axioms Voter.regular_consensus_probability
#print axioms Voter.color_consensus_probability
#print axioms Voter.sum_color_consensus_probability
#print axioms Voter.eventualColor_constant
#print axioms Voter.Examples.triangle_one_white
#print axioms Voter.Examples.biased_stationary
#print axioms Voter.Examples.wrightFisher_one_third
#print axioms Voter.Examples.twoVertex_cycle
#print axioms Voter.runRounds_eq_comp
#print axioms Voter.iterate_wfKernel_eq_expList
#print axioms Voter.expList_backward_ne
#print axioms Voter.iterate_disagreement_le
#print axioms Voter.voter_consensus_whp
#print axioms Voter.consensus_tendsto_of_selfLoop
#print axioms Voter.consensus_probability_of_selfLoop
#print axioms Voter.color_consensus_probability_of_selfLoop
#print axioms Voter.lazy_stationary_iff
#print axioms Voter.lazy_consensus_probability
#print axioms Voter.lazyNeighbor_consensus_probability
#print axioms Voter.wrightFisher_fixation_of_three_le
#print axioms Voter.wrightFisher_fixation
#print axioms Voter.iterate_disagreement_le_pairWalk
#print axioms Voter.iterate_disagreement_le_of_meeting
#print axioms Voter.lazy_meeting_le_half
#print axioms Voter.lazy_meeting_le_pow
#print axioms Voter.lazy_voter_consensus_whp
#print axioms Voter.potential_drift
#print axioms Voter.potential_drift_conductance
#print axioms Voter.lazy_consensus_of_minority
#print axioms Voter.lazy_consensus_conductance
#print axioms Voter.lazy_expected_consensus_time
#print axioms Voter.dynamic_consensus_conductance
#print axioms Voter.lazy_expected_consensus_time_many
#print axioms Voter.lazy_consensus_conductance_many
#print axioms Voter.potential_drift_mul
#print axioms Voter.lazy_consensus_conductance_sq
#print axioms Voter.lazy_consensus_conductance_sq_many
#print axioms Voter.lazy_expected_consensus_time_sq
#print axioms Voter.dynamic_consensus_conductance_sq
#print axioms Voter.dynamic_consensus_conductance_sq_many
#print axioms Voter.dynamic_consensus_conductance_min
#print axioms Voter.lazy_consensus_conductance_min
#print axioms Voter.doubleCover_connected
#print axioms Voter.plainPotential_drift
#print axioms Voter.plain_apart_mul_le
#print axioms Voter.plain_meeting_le_half
#print axioms Voter.plain_apart_le_pow
#print axioms Voter.plain_disagreement_le
#print axioms Voter.plain_voter_consensus_whp
