import ThreeMajority
#print axioms ThreeMajority.majority3_consensus_fail_le
#print axioms ThreeMajority.majority3_consensus_fail_le_clean
#print axioms ThreeMajority.majority3_consensus_whp
#print axioms ThreeMajority.stepCol_bool
#print axioms ThreeMajority.numColours_le_of_majorizes
#print axioms ThreeMajority.schurConvex_numColours_le
#print axioms ThreeMajority.multinomial_schurConvex
#print axioms ThreeMajority.ac_comparison
#print axioms ThreeMajority.ac_numColours
#print axioms ThreeMajority.alphaVoter_weight
#print axioms ThreeMajority.alpha3M_weight
#print axioms ThreeMajority.apply_ofStep_stepCol
#print axioms ThreeMajority.apply_ofStep_voterStep
#print axioms ThreeMajority.dominates_alpha3M_alphaVoter
#print axioms ThreeMajority.voter_le_threeMaj
#print axioms ThreeMajority.numColours_voterRun_le
#print axioms ThreeMajority.voter_dual
#print axioms ThreeMajority.walk_drift
#print axioms ThreeMajority.walk_drift_paper
#print axioms ThreeMajority.walk_expect_le
#print axioms ThreeMajority.voter_reduce_whp
#print axioms ThreeMajority.threeMaj_reduce_whp
#print axioms ThreeMajority.threeMaj_anyStart_consensus
