import Undecided
#print axioms Undecided.expected_count_a
#print axioms Undecided.expected_count_b
#print axioms Undecided.expected_count_u
#print axioms Undecided.expected_bias
#print axioms Undecided.step_of_mono
#print axioms Undecided.absorbed
#print axioms Undecided.majority_explicit
#print axioms Undecided.majority_whp
#print axioms Undecided.majority_whp_abs
#print axioms Undecided.majority_whp_of_ratio
#print axioms Undecided.Plurality.expected_count_some
#print axioms Undecided.Plurality.expected_count_none
#print axioms Undecided.Plurality.md_le_card
#print axioms Undecided.Plurality.one_le_md
#print axioms Undecided.Plurality.foldl_two
#print axioms Undecided.Plurality.plurality_explicit
#print axioms Undecided.Plurality.plurality_whp
#print axioms Undecided.Sequential.consensus_whp
#print axioms Undecided.Sequential.majority_whp
#print axioms Undecided.Sequential.approximate_majority
