import Averaging
#print axioms Averaging.degree_weighted_sum_step
#print axioms Averaging.avgStep_le
#print axioms Averaging.le_avgStep
#print axioms Averaging.tendsto_degAvg
#print axioms Averaging.not_tendsto_of_colorable
#print axioms Averaging.walkMatrix_pow_apply
#print axioms Averaging.avgIter_eq_walkMatrix_pow_mulVec
#print axioms Averaging.charpoly_walkMatrix
#print axioms Averaging.abs_walkMatrix_pow_sub_walkStationary_le
#print axioms Averaging.walkLambda_lt_one
#print axioms Averaging.abs_avgIter_sub_walkStationary_le
#print axioms Averaging.Sequential.edgeMatrix_mulVec
#print axioms Averaging.Sequential.edgeMatrix_mem_doublyStochastic
#print axioms Averaging.Sequential.transpose_edgeMatrix_mul_self
#print axioms Averaging.Sequential.avg_expect_edgeMatrix
#print axioms Averaging.Sequential.gossipMeanMatrix_of_isRegular
#print axioms Averaging.Sequential.avg_edgeMatrix
#print axioms Averaging.Sequential.meanMatrix_of_isRegular
#print axioms Averaging.Sequential.avg_transpose_edgeMatrix_mul_self
#print axioms Averaging.Sequential.avg_sum_sq_edgeMatrix_mulVec
#print axioms Averaging.Sequential.expList_seqRun
#print axioms Averaging.transitionMatrix_isHermitian
#print axioms Averaging.avgIter_eq_transitionMatrix_pow_mulVec
#print axioms Averaging.transitionMatrix_mulVec_clusterIndicator
#print axioms Averaging.abs_avgIter_sub_le
#print axioms Averaging.sign_avgIter_sub_eq
#print axioms Averaging.exists_sign_avgIter_sub_clusters
#print axioms Averaging.isStrongReconstruction_color
#print axioms Averaging.reconstructionTime_le
#print axioms Averaging.prob_dotProduct_clusterIndicator_eq_zero
#print axioms Averaging.choose_div_four_pow_le
#print axioms Averaging.strong_reconstruction
