import Averaging
#print axioms Averaging.degree_weighted_sum_step
#print axioms Averaging.avgStep_le
#print axioms Averaging.le_avgStep
#print axioms Averaging.tendsto_degAvg
#print axioms Averaging.not_tendsto_of_colorable
#print axioms Averaging.walkMatrix_pow_apply
#print axioms Averaging.avgIter_eq_walkMatrix_pow_mulVec
#print axioms Averaging.charpoly_walkMatrix
#print axioms Averaging.abs_walkMatrix_pow_sub_walkStationary_le
#print axioms Averaging.walkLambda_lt_one
#print axioms Averaging.abs_avgIter_sub_walkStationary_le
#print axioms Averaging.Sequential.edgeMatrix_mulVec
#print axioms Averaging.Sequential.edgeMatrix_mem_doublyStochastic
#print axioms Averaging.Sequential.transpose_edgeMatrix_mul_self
#print axioms Averaging.Sequential.avg_expect_edgeMatrix
#print axioms Averaging.Sequential.gossipMeanMatrix_of_isRegular
#print axioms Averaging.Sequential.avg_edgeMatrix
#print axioms Averaging.Sequential.meanMatrix_of_isRegular
#print axioms Averaging.Sequential.avg_transpose_edgeMatrix_mul_self
#print axioms Averaging.Sequential.avg_sum_sq_edgeMatrix_mulVec
#print axioms Averaging.Sequential.expList_seqRun
#print axioms Averaging.transitionMatrix_isHermitian
#print axioms Averaging.avgIter_eq_transitionMatrix_pow_mulVec
#print axioms Averaging.transitionMatrix_mulVec_clusterIndicator
#print axioms Averaging.abs_avgIter_sub_le
#print axioms Averaging.sign_avgIter_sub_eq
#print axioms Averaging.exists_sign_avgIter_sub_clusters
#print axioms Averaging.isStrongReconstruction_color
#print axioms Averaging.reconstructionTime_le
#print axioms Averaging.prob_dotProduct_clusterIndicator_eq_zero
#print axioms Averaging.choose_div_four_pow_le
#print axioms Averaging.strong_reconstruction
#print axioms Averaging.Opportunistic.avg_dart_edge
#print axioms Averaging.Opportunistic.oppRun_isSome_iff
#print axioms Averaging.Opportunistic.oppRun_getD
#print axioms Averaging.Opportunistic.sum_avgRun
#print axioms Averaging.Opportunistic.stepMatrix_mulVec
#print axioms Averaging.Opportunistic.stepMatrix_isSymm
#print axioms Averaging.Opportunistic.stepMatrix_mul_self
#print axioms Averaging.Opportunistic.avg_stepMatrix
#print axioms Averaging.Opportunistic.meanStepMatrix_isSymm
#print axioms Averaging.Opportunistic.meanStepMatrix_mem_doublyStochastic
#print axioms Averaging.Opportunistic.avg_edgeAvg
#print axioms Averaging.Opportunistic.expList_avgRun
#print axioms Averaging.Opportunistic.avg_sum_sq_edgeAvg
#print axioms Averaging.Opportunistic.meanStepMatrix_mulVec_cutVec
#print axioms Averaging.Opportunistic.expList_projCut
#print axioms Averaging.Opportunistic.expList_avgRun_decomp
#print axioms Averaging.Opportunistic.sum_sq_meanStepMatrix_pow_le
#print axioms Averaging.Opportunistic.monotone_criterion
#print axioms Averaging.Opportunistic.sign_criterion
#print axioms Averaging.Opportunistic.secondMoment_bound
#print axioms Averaging.Opportunistic.nonEphemeral_good
#print axioms Averaging.Opportunistic.sign_phase
#print axioms Averaging.Opportunistic.weakReconstruction_phase
#print axioms Averaging.Opportunistic.IsClusteredRegular.secondMoment_bound_aux
#print axioms Averaging.Opportunistic.IsClusteredRegular.prob_good_window
#print axioms Averaging.Opportunistic.IsClusteredRegular.prob_sign_window
#print axioms Averaging.Opportunistic.IsClusteredRegular.prob_weakReconstruction_window
#print axioms Averaging.Opportunistic.IsClusteredRegular.avg_restSq_edgeAvg_le
#print axioms Averaging.Opportunistic.IsClusteredRegular.avg_cutDev_edgeAvg_le
#print axioms Averaging.Opportunistic.IsClusteredRegular.expList_secondMoment_le
