import Epidemics
#print axioms Epidemics.infected_iff
#print axioms Epidemics.recovered_iff
#print axioms Epidemics.extinct
#print axioms Epidemics.final_recovered_iff
#print axioms Epidemics.coins_prob_open
#print axioms Epidemics.prob_infected_eq_prob_connected
#print axioms Epidemics.extinct_of_dist_lt
#print axioms Epidemics.Revisited.variance_card_le
#print axioms Epidemics.Revisited.connect_tail
#print axioms Epidemics.Revisited.connect_expect
#print axioms Epidemics.Revisited.growth_upper_tail
#print axioms Epidemics.Revisited.growth_upper_expect
#print axioms Epidemics.Revisited.overshoot_round
#print axioms Epidemics.Revisited.jumpProb_le
#print axioms Epidemics.Revisited.shrinking_upper_tail
#print axioms Epidemics.Revisited.shrinking_upper_expect
#print axioms Epidemics.Revisited.spreading_upper_tail
#print axioms Epidemics.Revisited.spreading_upper_expect
