import Epidemics
#print axioms Epidemics.infected_iff
#print axioms Epidemics.recovered_iff
#print axioms Epidemics.extinct
#print axioms Epidemics.final_recovered_iff
#print axioms Epidemics.coins_prob_open
#print axioms Epidemics.prob_infected_eq_prob_connected
#print axioms Epidemics.extinct_of_dist_lt
#print axioms Epidemics.KermackMcKendrick.IsSolution.sum_eq_one
#print axioms Epidemics.KermackMcKendrick.IsSolution.s_pos
#print axioms Epidemics.KermackMcKendrick.IsSolution.i_pos
#print axioms Epidemics.KermackMcKendrick.IsSolution.r_nonneg
#print axioms Epidemics.KermackMcKendrick.IsSolution.strictAntiOn_s
#print axioms Epidemics.KermackMcKendrick.IsSolution.strictMonoOn_r
#print axioms Epidemics.KermackMcKendrick.IsSolution.s_eq_mul_exp
#print axioms Epidemics.KermackMcKendrick.IsSolution.strictAntiOn_i
#print axioms Epidemics.KermackMcKendrick.IsSolution.initially_increasing_iff
#print axioms Epidemics.KermackMcKendrick.IsSolution.tendsto_i
#print axioms Epidemics.KermackMcKendrick.IsSolution.exists_tendsto_s
#print axioms Epidemics.KermackMcKendrick.IsSolution.tendsto_r
#print axioms Epidemics.KermackMcKendrick.IsSolution.final_size
#print axioms Epidemics.KermackMcKendrick.IsSolution.limit_pos
#print axioms Epidemics.KermackMcKendrick.IsSolution.R₀_mul_limit_lt_one
#print axioms Epidemics.KermackMcKendrick.IsSolution.final_size_unique
#print axioms Epidemics.KermackMcKendrick.IsSolution.final_size_unique_of_le_one
#print axioms Epidemics.KermackMcKendrick.IsSolution.exists_peak
#print axioms Epidemics.Revisited.variance_card_le
#print axioms Epidemics.Revisited.connect_tail
#print axioms Epidemics.Revisited.connect_expect
#print axioms Epidemics.Revisited.growth_upper_tail
#print axioms Epidemics.Revisited.growth_upper_expect
#print axioms Epidemics.Revisited.overshoot_round
#print axioms Epidemics.Revisited.jumpProb_le
#print axioms Epidemics.Revisited.shrinking_upper_tail
#print axioms Epidemics.Revisited.shrinking_upper_expect
#print axioms Epidemics.Revisited.spreading_upper_tail
#print axioms Epidemics.Revisited.spreading_upper_expect
